### ISSUE TITLE
Support CHARLABELS and STATELABELS in addition to currently supported CHARSTATELABELS

### ISSUE THREAD

**Issue by kleintom** [mjy/nexus_parser#11]
Based on the same small sample, it looks like morphobank nexus files use separate CHARLABELS and STATELABELS blocks instead of the combined CHARSTATELABELS that nexus_parser currently supports.

When the parser doesn't recognize those blocks it winds up in an infinite loop which eventually ends in an error message about too many characters (iirc).

Is this something you want to support?

**Comment by mjy** [comment]
This one might be trickier.  I think the question is 1) do both formats "just work" in Mesquite and 2) what does a trip through Mesquite produce (using simple export)? We'll have to test that to answer this question.  

We have previously asserted that one may have to run files through Mesquite as a pre-processor (de-facto validator), I'm OK with "enforcing" this approach or leaning towards it rather than extending functionality here, however I'm also OK with "simple" Token extensions if those can be used.  Here if we have to process two blocks the code might be (slightly) tricker to extend (but again, I haven't looked at it for 10+ years).

Ping @DMaddison

**Comment by kleintom** [comment]
I defer to [DMaddison](https://github.com/DMaddison) of course, but I'm seeing CHARLABELS/STATELABELS turned into CHARSTATELABELS when I do `Export / NEXUS file` in mesquite.

I haven't looked at how extending support might go yet either.

**Comment by mjy** [comment]
>  but I'm seeing CHARLABELS/STATELABELS turned into CHARSTATELABELS when I do Export / NEXUS file in mesquite.

Perfect, then we don't need to support the paired version for now, users can filter through Mesquite.

**Comment by kleintom** [comment]
At a quick look at least this actually looks pretty straightforward, if you want to hold off on the next release I should hopefully have something later today.  All of morphobank's nexus files are in this format, so it would be nice to get this.

**Comment by mjy** [comment]
Sounds good, holding.
